### ISSUE TITLE
"Add Calendar" button on /events links to undefined calendar

### ISSUE THREAD

**Issue by joehewett** [WarwickAI/wai-platform-v2#16]
https://warwick.ai/events

image

This links to https://calendar.google.com/calendar/r?cid=undefined

It should link to https://calendar.google.com/calendar/u/0/r?cid=16gnvov94ele73k1e7ekbaqr08@group.calendar.google.com

While we're at it, can we add another Add Calendar button in our style (big green button) above the calendar? It would be more visible

**Comment by Edward-Upton** [comment]
Seems like this may be an issue with Google updating how calendar links work. To fix I think I'll just replace their button with our own with a link to the calendar

**Comment by Edward-Upton** [comment]
Will still show the add calendar button at the bottom, but the top button is a lot more obvious. I do want to switch the calendar at some point anyway.

**Comment by Edward-Upton** [comment]
Done in dfdf87b4f4a04f545549e3938c64e73dcc5f71ec, will push to production later after some more fixes/updates.
