### ISSUE TITLE
Change "Become A Researcher" on landing page

### ISSUE THREAD

**Issue by ojaffe** [WarwickAI/wai-platform-v2#75]
Change "Become a Researcher" to something different; researcher applications are closed now.

![image](https://user-images.githubusercontent.com/28544674/199548613-1b79bce0-1327-4261-9d9d-8749cbca9410.png)

Change back to "Join a course", sub-text "Sign up to any of our courses here!"

**Comment by pluv1** [comment]
The banner on the blog page could also be removed 
![image](https://user-images.githubusercontent.com/109678416/199700978-7ea12877-e6ff-4d55-9f4c-16cb02e1c58d.png)

**Comment by ojaffe** [comment]
Changing my original suggestion to:
"Join Our Team!"
"Sign up to be a projects exec"

Pointing to this link
https://forms.gle/DPuiUXSm33NrQjko9

**Comment by Edward-Upton** [comment]
Resolve in 006ca47 and 8468c60
